### ISSUE TITLE
Don't need to specify AWS keys.

### ISSUE THREAD

**Issue by tristanmorgan** [vibrato/packer-bamboo-agent#1]
Hi John,

You don't need to specify AWS keys as variables in the packer json, packer will pull them from environment variables (same goes for terraform and the vagrant-aws provider too). I'm pretty sure it works when you use an aws-session-token too. (time based OTP and assume-role...)

Cheers,

T.

**Comment by ghost** [comment]
Thanks Tristan. I have fixed the packer json by removing the AWS variables. I have updated the readme on how to pull AWS credentials from the environment or local credentials file.
